### ISSUE TITLE
Is there any documentation available for this?

### ISSUE THREAD

**Issue by KisorAlaguvel** [wilselby/MatlabQuadSimAP#1]
Can I have any (available) complete guide for this?
I want to develop a new type of Drone frame with MATLAB.

**Comment by KisorAlaguvel** [comment]
Is this MATLAB model a ready-to-implement one? I mean, how are sensors integrated in the script? How to make this script arduino-based?

**Comment by wilselby** [comment]
Here is all my documentation:
https://www.wilselby.com/research/arducopter/
